using InstaRound
using Test

@testset "No Names" begin
    @test round(IGRound, 999; names=false) == "999"
    @test round(IGRound, BigInt(10) ^ 3; names=false) == "1.0K"
    @test round(IGRound, BigInt(10) ^ 4; names=false) == "10.0K"
    @test round(IGRound, BigInt(10) ^ 5; names=false) == "100.0K"
    @test round(IGRound, BigInt(10) ^ 6; names=false) == "1.0M"
    @test round(IGRound, BigInt(10) ^ 7; names=false) == "10.0M"
    @test round(IGRound, BigInt(10) ^ 8; names=false) == "100.0M"
    @test round(IGRound, BigInt(10) ^ 9; names=false) == "1.0B"
    @test round(IGRound, BigInt(10) ^ 10; names=false) == "10.0B"
    @test round(IGRound, BigInt(10) ^ 11; names=false) == "100.0B"
    @test round(IGRound, BigInt(10) ^ 12; names=false) == "1.0t"
    @test round(IGRound, BigInt(10) ^ 13; names=false) == "10.0t"
    @test round(IGRound, BigInt(10) ^ 14; names=false) == "100.0t"
    @test round(IGRound, BigInt(10) ^ 15; names=false) == "1.0q"
    @test round(IGRound, BigInt(10) ^ 16; names=false) == "10.0q"
    @test round(IGRound, BigInt(10) ^ 17; names=false) == "100.0q"
    @test round(IGRound, BigInt(10) ^ 18; names=false) == "1.0Q"
    @test round(IGRound, BigInt(10) ^ 19; names=false) == "10.0Q"
    @test round(IGRound, BigInt(10) ^ 20; names=false) == "100.0Q"
    @test round(IGRound, BigInt(10) ^ 21; names=false) == "1.0s"
    @test round(IGRound, BigInt(10) ^ 22; names=false) == "10.0s"
    @test round(IGRound, BigInt(10) ^ 23; names=false) == "100.0s"
    @test round(IGRound, BigInt(10) ^ 24; names=false) == "1.0S"
    @test round(IGRound, BigInt(10) ^ 25; names=false) == "10.0S"
    @test round(IGRound, BigInt(10) ^ 26; names=false) == "100.0S"
    @test round(IGRound, BigInt(10) ^ 27; names=false) == "1.0o"
    @test round(IGRound, BigInt(10) ^ 28; names=false) == "10.0o"
    @test round(IGRound, BigInt(10) ^ 29; names=false) == "100.0o"
    @test round(IGRound, BigInt(10) ^ 30; names=false) == "1.0n"
    @test round(IGRound, BigInt(10) ^ 31; names=false) == "10.0n"
    @test round(IGRound, BigInt(10) ^ 32; names=false) == "100.0n"
    @test round(IGRound, BigInt(10) ^ 33; names=false) == "1.0d"
    @test round(IGRound, BigInt(10) ^ 34; names=false) == "10.0d"
    @test round(IGRound, BigInt(10) ^ 35; names=false) == "100.0d"
    @test round(IGRound, BigInt(10) ^ 36; names=false) == "1.0U"
    @test round(IGRound, BigInt(10) ^ 37; names=false) == "10.0U"
    @test round(IGRound, BigInt(10) ^ 38; names=false) == "100.0U"
    @test round(IGRound, BigInt(10) ^ 39; names=false) == "1.0D"
    @test round(IGRound, BigInt(10) ^ 40; names=false) == "10.0D"
    @test round(IGRound, BigInt(10) ^ 41; names=false) == "100.0D"
    @test round(IGRound, BigInt(10) ^ 42; names=false) == "1.0T"
    @test round(IGRound, BigInt(10) ^ 43; names=false) == "10.0T"
    @test round(IGRound, BigInt(10) ^ 44; names=false) == "100.0T"
    @test round(IGRound, BigInt(10) ^ 45; names=false) == "1.0Qt"
    @test round(IGRound, BigInt(10) ^ 46; names=false) == "10.0Qt"
    @test round(IGRound, BigInt(10) ^ 47; names=false) == "100.0Qt"
    @test round(IGRound, BigInt(10) ^ 48; names=false) == "1.0Qd"
    @test round(IGRound, BigInt(10) ^ 49; names=false) == "10.0Qd"
    @test round(IGRound, BigInt(10) ^ 50; names=false) == "100.0Qd"
    @test round(IGRound, BigInt(10) ^ 51; names=false) == "1.0Sd"
    @test round(IGRound, BigInt(10) ^ 52; names=false) == "10.0Sd"
    @test round(IGRound, BigInt(10) ^ 53; names=false) == "100.0Sd"
    @test round(IGRound, BigInt(10) ^ 54; names=false) == "1.0St"
    @test round(IGRound, BigInt(10) ^ 55; names=false) == "10.0St"
    @test round(IGRound, BigInt(10) ^ 56; names=false) == "100.0St"
    @test round(IGRound, BigInt(10) ^ 57; names=false) == "1.0O"
    @test round(IGRound, BigInt(10) ^ 58; names=false) == "10.0O"
    @test round(IGRound, BigInt(10) ^ 59; names=false) == "100.0O"
    @test round(IGRound, BigInt(10) ^ 60; names=false) == "1.0N"
    @test round(IGRound, BigInt(10) ^ 61; names=false) == "10.0N"
    @test round(IGRound, BigInt(10) ^ 62; names=false) == "100.0N"
    @test round(IGRound, BigInt(10) ^ 63; names=false) == "1.0v"
    @test round(IGRound, BigInt(10) ^ 64; names=false) == "10.0v"
    @test round(IGRound, BigInt(10) ^ 65; names=false) == "100.0v"
    @test round(IGRound, BigInt(10) ^ 66; names=false) == "1.0c"
    @test round(IGRound, BigInt(10) ^ 67; names=false) == "10.0c"
    @test round(IGRound, BigInt(10) ^ 68; names=false) == "100.0c"
end


@testset "With Names" begin
    @test round(IGRound, 999; names=true) == "999"
    @test round(IGRound, BigInt(10) ^ 3; names=true) == "1.0 Thousand"
    @test round(IGRound, BigInt(10) ^ 4; names=true) == "10.0 Thousand"
    @test round(IGRound, BigInt(10) ^ 5; names=true) == "100.0 Thousand"
    @test round(IGRound, BigInt(10) ^ 6; names=true) == "1.0 Million"
    @test round(IGRound, BigInt(10) ^ 7; names=true) == "10.0 Million"
    @test round(IGRound, BigInt(10) ^ 8; names=true) == "100.0 Million"
    @test round(IGRound, BigInt(10) ^ 9; names=true) == "1.0 Billion"
    @test round(IGRound, BigInt(10) ^ 10; names=true) == "10.0 Billion"
    @test round(IGRound, BigInt(10) ^ 11; names=true) == "100.0 Billion"
    @test round(IGRound, BigInt(10) ^ 12; names=true) == "1.0 Trillion"
    @test round(IGRound, BigInt(10) ^ 13; names=true) == "10.0 Trillion"
    @test round(IGRound, BigInt(10) ^ 14; names=true) == "100.0 Trillion"
    @test round(IGRound, BigInt(10) ^ 15; names=true) == "1.0 Quadrillion"
    @test round(IGRound, BigInt(10) ^ 16; names=true) == "10.0 Quadrillion"
    @test round(IGRound, BigInt(10) ^ 17; names=true) == "100.0 Quadrillion"
    @test round(IGRound, BigInt(10) ^ 18; names=true) == "1.0 Quintillion"
    @test round(IGRound, BigInt(10) ^ 19; names=true) == "10.0 Quintillion"
    @test round(IGRound, BigInt(10) ^ 20; names=true) == "100.0 Quintillion"
    @test round(IGRound, BigInt(10) ^ 21; names=true) == "1.0 Sextillion"
    @test round(IGRound, BigInt(10) ^ 22; names=true) == "10.0 Sextillion"
    @test round(IGRound, BigInt(10) ^ 23; names=true) == "100.0 Sextillion"
    @test round(IGRound, BigInt(10) ^ 24; names=true) == "1.0 Septillion"
    @test round(IGRound, BigInt(10) ^ 25; names=true) == "10.0 Septillion"
    @test round(IGRound, BigInt(10) ^ 26; names=true) == "100.0 Septillion"
    @test round(IGRound, BigInt(10) ^ 27; names=true) == "1.0 Octillion"
    @test round(IGRound, BigInt(10) ^ 28; names=true) == "10.0 Octillion"
    @test round(IGRound, BigInt(10) ^ 29; names=true) == "100.0 Octillion"
    @test round(IGRound, BigInt(10) ^ 30; names=true) == "1.0 Nonillion"
    @test round(IGRound, BigInt(10) ^ 31; names=true) == "10.0 Nonillion"
    @test round(IGRound, BigInt(10) ^ 32; names=true) == "100.0 Nonillion"
    @test round(IGRound, BigInt(10) ^ 33; names=true) == "1.0 Decillion"
    @test round(IGRound, BigInt(10) ^ 34; names=true) == "10.0 Decillion"
    @test round(IGRound, BigInt(10) ^ 35; names=true) == "100.0 Decillion"
    @test round(IGRound, BigInt(10) ^ 36; names=true) == "1.0 Undecillion"
    @test round(IGRound, BigInt(10) ^ 37; names=true) == "10.0 Undecillion"
    @test round(IGRound, BigInt(10) ^ 38; names=true) == "100.0 Undecillion"
    @test round(IGRound, BigInt(10) ^ 39; names=true) == "1.0 Duodecillion"
    @test round(IGRound, BigInt(10) ^ 40; names=true) == "10.0 Duodecillion"
    @test round(IGRound, BigInt(10) ^ 41; names=true) == "100.0 Duodecillion"
    @test round(IGRound, BigInt(10) ^ 42; names=true) == "1.0 Tredecillion"
    @test round(IGRound, BigInt(10) ^ 43; names=true) == "10.0 Tredecillion"
    @test round(IGRound, BigInt(10) ^ 44; names=true) == "100.0 Tredecillion"
    @test round(IGRound, BigInt(10) ^ 45; names=true) == "1.0 Quattuordecillion"
    @test round(IGRound, BigInt(10) ^ 46; names=true) == "10.0 Quattuordecillion"
    @test round(IGRound, BigInt(10) ^ 47; names=true) == "100.0 Quattuordecillion"
    @test round(IGRound, BigInt(10) ^ 48; names=true) == "1.0 Quindecillion"
    @test round(IGRound, BigInt(10) ^ 49; names=true) == "10.0 Quindecillion"
    @test round(IGRound, BigInt(10) ^ 50; names=true) == "100.0 Quindecillion"
    @test round(IGRound, BigInt(10) ^ 51; names=true) == "1.0 Sexdecillion"
    @test round(IGRound, BigInt(10) ^ 52; names=true) == "10.0 Sexdecillion"
    @test round(IGRound, BigInt(10) ^ 53; names=true) == "100.0 Sexdecillion"
    @test round(IGRound, BigInt(10) ^ 54; names=true) == "1.0 Septendecillion"
    @test round(IGRound, BigInt(10) ^ 55; names=true) == "10.0 Septendecillion"
    @test round(IGRound, BigInt(10) ^ 56; names=true) == "100.0 Septendecillion"
    @test round(IGRound, BigInt(10) ^ 57; names=true) == "1.0 Octodecillion"
    @test round(IGRound, BigInt(10) ^ 58; names=true) == "10.0 Octodecillion"
    @test round(IGRound, BigInt(10) ^ 59; names=true) == "100.0 Octodecillion"
    @test round(IGRound, BigInt(10) ^ 60; names=true) == "1.0 Novemdecillion"
    @test round(IGRound, BigInt(10) ^ 61; names=true) == "10.0 Novemdecillion"
    @test round(IGRound, BigInt(10) ^ 62; names=true) == "100.0 Novemdecillion"
    @test round(IGRound, BigInt(10) ^ 63; names=true) == "1.0 Vigintillion"
    @test round(IGRound, BigInt(10) ^ 64; names=true) == "10.0 Vigintillion"
    @test round(IGRound, BigInt(10) ^ 65; names=true) == "100.0 Vigintillion"
    @test round(IGRound, BigInt(10) ^ 66; names=true) == "1.0 Unvigintillion"
    @test round(IGRound, BigInt(10) ^ 67; names=true) == "10.0 Unvigintillion"
    @test round(IGRound, BigInt(10) ^ 68; names=true) == "100.0 Unvigintillion"
end

@testset "With floating points" begin
    @test round(IGRound, 4_123_456) == "4.12M"
end